[package]
name = "nats-repro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nats = "0.18.1"
env_logger = "0.9.0"
log = "0.4"
